// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radar_CRM.Data;

#nullable disable

namespace Radar_CRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902075606_onchanges")]
    partial class onchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Radar_CRM.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AlternateEmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AveragePatientFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClinicType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact1Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact2Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact3Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentSoftwareName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyUsingSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasComputer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDuplicated")
                        .HasColumnType("bit");

                    b.Property<string>("IsHomeopathicDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaCampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfClinics")
                        .HasColumnType("int");

                    b.Property<int?>("PatientsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductPurchased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfileCompletionPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePendingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualificationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeminarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalExperience")
                        .HasColumnType("int");

                    b.Property<string>("WorkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfPassing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsOfPractice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Radar_CRM.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Adjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AlternateEmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AveragePatientFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CampaignSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact1Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact2Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact3Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentSoftwareName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyUsingSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DealValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DemoOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExpectedRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FirstCallDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasComputer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestedPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsHomeopathicDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastContactDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeadCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LostReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaCampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberOfClinics")
                        .HasColumnType("int");

                    b.Property<string>("PackageSelected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pipeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Probability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadarOpusLicenseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadarOpusVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeminarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialLeadID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TimePeriodToBuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalExperience")
                        .HasColumnType("int");

                    b.Property<string>("WorkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfPassing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearOfPractice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("Radar_CRM.Models.Notes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Radar_CRM.Models.ProductPaymentRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("ProductPaymentRow");
                });

            modelBuilder.Entity("Radar_CRM.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Radar_CRM.Models.User", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AddedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ConfirmationStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryLocale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentShiftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grouping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextShiftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredCurrencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredUnitForDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingToId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SalesCallAssign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShiftEffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("SortOrderPreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Radar_CRM.Models.ProductPaymentRow", b =>
                {
                    b.HasOne("Radar_CRM.Models.Lead", "Lead")
                        .WithMany("PaymentRows")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Radar_CRM.Models.User", b =>
                {
                    b.HasOne("Radar_CRM.Models.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Radar_CRM.Models.Lead", b =>
                {
                    b.Navigation("PaymentRows");
                });
#pragma warning restore 612, 618
        }
    }
}
