// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radar_CRM.Data;

#nullable disable

namespace Radar_CRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910111952_taskfifthtest")]
    partial class taskfifthtest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Radar_CRM.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AlternateEmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AveragePatientFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClinicType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact1Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact2Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact3Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentSoftwareName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyUsingSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasComputer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDuplicated")
                        .HasColumnType("bit");

                    b.Property<string>("IsHomeopathicDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaCampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfClinics")
                        .HasColumnType("int");

                    b.Property<int?>("PatientsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductPurchased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfileCompletionPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePendingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfileRate")
                        .HasColumnType("int");

                    b.Property<string>("Profilestatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualificationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeminarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalExperience")
                        .HasColumnType("int");

                    b.Property<string>("WorkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfPassing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsOfPractice")
                        .HasColumnType("int");

                    b.Property<string>("ZohoRecordId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountOwnerId");

                    b.HasIndex("CoOwnerId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Radar_CRM.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Adjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovalRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DemoOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LeadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaCampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ZohoRecordId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DealOwnerId");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("Radar_CRM.Models.DealNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("DealNotes");
                });

            modelBuilder.Entity("Radar_CRM.Models.DealPaymentRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("DealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("DealPaymentRows");
                });

            modelBuilder.Entity("Radar_CRM.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AccountOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Adjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AlternateEmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AveragePatientFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CampaignSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact1Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact2Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact3Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentSoftwareName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyUsingSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DealValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DemoOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DemoScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExpectedRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FirstCallDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasComputer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestedPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsHomeopathicDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastContactDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeadCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LeadProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LostReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaCampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberOfClinics")
                        .HasColumnType("int");

                    b.Property<string>("PackageSelected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pipeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Probability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadarOpusLicenseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadarOpusVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeminarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialLeadID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TimePeriodToBuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalExperience")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TrialEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TrialStartDate")
                        .HasColumnType("date");

                    b.Property<string>("WorkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfPassing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearOfPractice")
                        .HasColumnType("int");

                    b.Property<string>("ZohoRecordId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountOwnerId");

                    b.HasIndex("CoOwnerId");

                    b.HasIndex("DemoOwnerId");

                    b.HasIndex("LeadOwnerId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("Radar_CRM.Models.Notes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("NoteOwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("ZohoRecordId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DealId");

                    b.HasIndex("LeadId");

                    b.HasIndex("NoteOwnerId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Radar_CRM.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChangeLogTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConnectedToId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectedToModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ProductActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductOwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QtyOrdered")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityInDemand")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SalesEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SalesStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SupportEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SupportStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Taxable")
                        .HasColumnType("bit");

                    b.Property<decimal?>("USD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsageUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Radar_CRM.Models.ProductPaymentRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("DealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("LeadId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPaymentRows");
                });

            modelBuilder.Entity("Radar_CRM.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Radar_CRM.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ChangeLogTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClosedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("LeadStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedToId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Reminder")
                        .HasColumnType("datetime2");

                    b.Property<string>("Repeat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskOwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DealId");

                    b.HasIndex("LeadId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Radar_CRM.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AddedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ConfirmationStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryLocale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentShiftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grouping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextShiftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredCurrencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredUnitForDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingToId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SalesCallAssign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShiftEffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("SortOrderPreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Radar_CRM.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChangeLogTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectedToId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectedToModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailOptOut")
                        .HasColumnType("bit");

                    b.Property<string>("GLAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GstNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsubscribedMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UnsubscribedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorOwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Radar_CRM.Models.Account", b =>
                {
                    b.HasOne("Radar_CRM.Models.User", "AccountOwner")
                        .WithMany("OwnedAccounts")
                        .HasForeignKey("AccountOwnerId");

                    b.HasOne("Radar_CRM.Models.User", "CoOwner")
                        .WithMany()
                        .HasForeignKey("CoOwnerId");

                    b.Navigation("AccountOwner");

                    b.Navigation("CoOwner");
                });

            modelBuilder.Entity("Radar_CRM.Models.Deal", b =>
                {
                    b.HasOne("Radar_CRM.Models.Account", "Account")
                        .WithMany("Contacts")
                        .HasForeignKey("AccountId");

                    b.HasOne("Radar_CRM.Models.User", "DealOwner")
                        .WithMany("OwnedDeals")
                        .HasForeignKey("DealOwnerId");

                    b.Navigation("Account");

                    b.Navigation("DealOwner");
                });

            modelBuilder.Entity("Radar_CRM.Models.DealNote", b =>
                {
                    b.HasOne("Radar_CRM.Models.Deal", "Deal")
                        .WithMany("Note")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("Radar_CRM.Models.DealPaymentRow", b =>
                {
                    b.HasOne("Radar_CRM.Models.Deal", "Deal")
                        .WithMany("PaymentRows")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("Radar_CRM.Models.Lead", b =>
                {
                    b.HasOne("Radar_CRM.Models.Account", "Account")
                        .WithMany("Leads")
                        .HasForeignKey("AccountId");

                    b.HasOne("Radar_CRM.Models.User", "AccountOwner")
                        .WithMany()
                        .HasForeignKey("AccountOwnerId");

                    b.HasOne("Radar_CRM.Models.User", "CoOwner")
                        .WithMany()
                        .HasForeignKey("CoOwnerId");

                    b.HasOne("Radar_CRM.Models.User", "DemoOwner")
                        .WithMany()
                        .HasForeignKey("DemoOwnerId");

                    b.HasOne("Radar_CRM.Models.User", "LeadOwner")
                        .WithMany("OwnedLeads")
                        .HasForeignKey("LeadOwnerId");

                    b.Navigation("Account");

                    b.Navigation("AccountOwner");

                    b.Navigation("CoOwner");

                    b.Navigation("DemoOwner");

                    b.Navigation("LeadOwner");
                });

            modelBuilder.Entity("Radar_CRM.Models.Notes", b =>
                {
                    b.HasOne("Radar_CRM.Models.Account", "Account")
                        .WithMany("Note")
                        .HasForeignKey("AccountId");

                    b.HasOne("Radar_CRM.Models.Deal", "Deal")
                        .WithMany("Notes")
                        .HasForeignKey("DealId");

                    b.HasOne("Radar_CRM.Models.Lead", "Lead")
                        .WithMany("Notes")
                        .HasForeignKey("LeadId");

                    b.HasOne("Radar_CRM.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.HasOne("Radar_CRM.Models.User", "NoteOwner")
                        .WithMany()
                        .HasForeignKey("NoteOwnerId");

                    b.Navigation("Account");

                    b.Navigation("Deal");

                    b.Navigation("Lead");

                    b.Navigation("NoteOwner");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Radar_CRM.Models.ProductPaymentRow", b =>
                {
                    b.HasOne("Radar_CRM.Models.Account", "Account")
                        .WithMany("PaymentRows")
                        .HasForeignKey("AccountId");

                    b.HasOne("Radar_CRM.Models.Lead", "Lead")
                        .WithMany("PaymentRow")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Radar_CRM.Models.Product", "Product")
                        .WithMany("PaymentRows")
                        .HasForeignKey("ProductId");

                    b.Navigation("Account");

                    b.Navigation("Lead");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Radar_CRM.Models.Task", b =>
                {
                    b.HasOne("Radar_CRM.Models.Account", null)
                        .WithMany("Tasks")
                        .HasForeignKey("AccountId");

                    b.HasOne("Radar_CRM.Models.Deal", null)
                        .WithMany("Tasks")
                        .HasForeignKey("DealId");

                    b.HasOne("Radar_CRM.Models.Lead", null)
                        .WithMany("Tasks")
                        .HasForeignKey("LeadId");

                    b.HasOne("Radar_CRM.Models.User", null)
                        .WithMany("OwnedContacts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Radar_CRM.Models.User", b =>
                {
                    b.HasOne("Radar_CRM.Models.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Radar_CRM.Models.Account", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Leads");

                    b.Navigation("Note");

                    b.Navigation("PaymentRows");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Radar_CRM.Models.Deal", b =>
                {
                    b.Navigation("Note");

                    b.Navigation("Notes");

                    b.Navigation("PaymentRows");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Radar_CRM.Models.Lead", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PaymentRow");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Radar_CRM.Models.Product", b =>
                {
                    b.Navigation("PaymentRows");
                });

            modelBuilder.Entity("Radar_CRM.Models.User", b =>
                {
                    b.Navigation("OwnedAccounts");

                    b.Navigation("OwnedContacts");

                    b.Navigation("OwnedDeals");

                    b.Navigation("OwnedLeads");
                });
#pragma warning restore 612, 618
        }
    }
}
