// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radar_CRM.Data;

#nullable disable

namespace Radar_CRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826103852_newmodule")]
    partial class newmodule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Radar_CRM.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr1_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_FlatHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2_Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AlternateEmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AveragePatientFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClinicType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact1Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact2Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact3Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentSoftwareName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyUsingSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasComputer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDuplicated")
                        .HasColumnType("bit");

                    b.Property<string>("IsHomeopathicDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfClinics")
                        .HasColumnType("int");

                    b.Property<int?>("PatientsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductPurchased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfileCompletionPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePendingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualificationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalExperience")
                        .HasColumnType("int");

                    b.Property<string>("WorkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfPassing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsOfPractice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
